/**
 * Encoder script for words.js
 * Usage: node encode-words.js
 * 
 * This script reads words.js and generates an encoded version
 * to prevent casual inspection of answers.
 */

const fs = require('fs');

// Simple but effective encoding function
function encode(text, key = 'hkd2024') {
    let encoded = '';
    for (let i = 0; i < text.length; i++) {
        const charCode = text.charCodeAt(i);
        const keyChar = key.charCodeAt(i % key.length);
        const encodedChar = String.fromCharCode(charCode ^ keyChar);
        // Convert to hex to handle special characters
        encoded += encodedChar.charCodeAt(0).toString(16).padStart(4, '0');
    }
    return encoded;
}

// Read the source file
const sourcePath = 'words.js';
if (!fs.existsSync(sourcePath)) {
    console.error('Error: words.js not found');
    process.exit(1);
}

// Read and parse the source file to get the words array
let words;
try {
    // Read the file content
    const fileContent = fs.readFileSync(sourcePath, 'utf8');
    
    // Extract the array content - match everything between [ and ];
    const arrayMatch = fileContent.match(/const words = (\[.*\]);/s);
    if (!arrayMatch) {
        throw new Error('Could not find words array in source file');
    }
    
    // Parse the array content
    words = eval(arrayMatch[1]);
    
    if (!Array.isArray(words)) {
        throw new Error('Could not parse words array');
    }
} catch (error) {
    console.error('Error reading words.js:', error.message);
    process.exit(1);
}

// Encode each word entry
const encodedWords = words.map(word => ({
    h: encode(word.hraswa),
    d: encode(word.dirgha),
    c: word.correct
}));

// Generate the output file content
const output = `// Encoded words file - generated by encode-words.js
// DO NOT EDIT THIS FILE DIRECTLY
// Edit words.js and run: node encode-words.js

const encodedWords = ${JSON.stringify(encodedWords, null, 4)};
`;

// Write the output file
const outputPath = 'words.encoded.js';
fs.writeFileSync(outputPath, output, 'utf8');

console.log(`✓ Encoded ${words.length} words`);
console.log(`✓ Generated: ${outputPath}`);
console.log('\nNote: The decoder is in script.js');
console.log('This file contains only the encoded data.');
